import OpenAI from 'openai';
import {requireWorkspace,sendWorkspaceError} from './_lib/authenticated-workspace.js';
import {assertAndConsumeUsage,sendBillingError} from './_lib/billing.js';
const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});

const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));

const isTemporaryOpenAIError=error=>{
  const status=Number(error?.status||0);
  const code=String(error?.code||error?.error?.code||'').toLowerCase();
  if(code==='insufficient_quota'||code==='billing_hard_limit_reached')return false;
  return status===429||status===408||status===409||status>=500;
};

const json=async(prompt,images=[],imageDetail='high')=>{
  const content=[
    {type:'input_text',text:prompt},
    ...images.map(url=>({
      type:'input_image',
      image_url:url,
      detail:imageDetail
    }))
  ];

  let lastError;

  for(let attempt=0;attempt<5;attempt++){
    try{
      const r=await client.responses.create({
        model:process.env.OPENAI_VISION_MODEL||'gpt-4.1',
        input:[{role:'user',content}],
        text:{format:{type:'json_object'}}
      });

      return JSON.parse(r.output_text);
    }catch(error){
      lastError=error;

      if(!isTemporaryOpenAIError(error)||attempt===4){
        throw error;
      }

      const retryAfterSeconds=Number(
        error?.headers?.['retry-after']||
        error?.headers?.get?.('retry-after')||
        0
      );

      const delay=retryAfterSeconds>0
        ? retryAfterSeconds*1000
        : Math.min(20000,1500*(2**attempt))+Math.floor(Math.random()*700);

      console.warn(`OpenAI request paused before retry ${attempt+2} of 5.`);
      await wait(delay);
    }
  }

  throw lastError;
};
const captionPolicy=(context={},profile={})=>`
CAPTION VOICE AND STRUCTURE RULES

Use all available voice evidence in this order:
1. Connected Instagram analysis, when supplied.
2. Website brand analysis, when supplied.
3. The saved voice profile.
4. Basic onboarding details.

The final wording must sound as though the customer wrote it themselves.
It must not sound generic, over-produced, formulaic or generated by artificial intelligence.

Never use any dash or hyphen character anywhere in a caption.
This includes em dashes, en dashes, hyphenated compound words, spaced hyphens and dash-led sentence fragments.
Rewrite compound wording naturally, for example use "city centre" instead of "city-centre" and "behind the scenes" instead of "behind-the-scenes".
Use full stops, commas or separate sentences instead.

Avoid artificial marketing phrases including:
"whether you're", "elevate", "showcase", "unforgettable", "stunning",
"perfect backdrop", "ideal setting", "something special", "memories that last",
"where moments are made", "designed to impress", "bringing your vision to life",
"look no further", "we've got you covered", "take it to the next level".

Do not use the same sentence structure across all three options.
Do not force emojis, questions, hashtags or calls to action.
Match the business's normal vocabulary, formality, energy, emoji use and sentence length.

Return exactly three caption choices with these labels:
1. Engaging
2. Informative
3. Enquiry focused

Engaging:
Sound natural and conversational.
Use 8 to 35 words.
It may ask one easy relevant question, but only when that feels natural.
Do not add the website unless it is essential to the post.

Informative:
Use 30 to 90 words when enough verified information is available.
Add useful service, product, location, customer benefit or trust information from the supplied website analysis.
Do not invent details that are not present in the image, website analysis or onboarding information.
Do not automatically add the website.

Enquiry focused:
Use 25 to 80 words.
Connect the post naturally to the business goal and give one clear next step.
It must still sound human and not like an advert.
Only include the website when all of these are true:
the account type is Business,
a valid website was supplied,
the post has a genuine commercial or enquiry purpose,
and directing the reader to the website is relevant.
When used, place the clean website domain alone on the final line.
Do not add a website for Individual accounts.

Website supplied: ${context.website||'None'}
Account type: ${context.accountType||'Unknown'}
Caption intelligence: ${JSON.stringify(context.captionIntelligence||{})}
Saved profile: ${JSON.stringify(profile||{})}
`;
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});if(!process.env.OPENAI_API_KEY)return res.status(500).json({error:'OPENAI_API_KEY is missing.'});try{const {supabase,workspace}=await requireWorkspace(req);const {action,context,profile,image,images,group,screenshots}=req.body||{};
if(action==='image')await assertAndConsumeUsage({supabase,workspaceId:workspace.id,metric:'image_analyses',quantity:1});
if(action==='validate')await assertAndConsumeUsage({supabase,workspaceId:workspace.id,metric:'caption_regenerations',quantity:1});
if(action==='profile'){const p=await json(`You are PicPlanr creating an initial account understanding from onboarding details only. Use British English. Do not infer an industry, niche, service, audience, competitor strategy or brand personality that was not explicitly supplied. Context: ${JSON.stringify(context)}. Return JSON with summary string, voice_traits array of 4 strings, content_direction string, writing_rules string, confidence_note string, and needs_more_information boolean. The summary must describe only supplied facts. If information is incomplete, say so clearly. Do not use em dashes or American spelling.`);return res.json({profile:p})}
if(action==='audit'){const shotList=Array.isArray(screenshots)?screenshots.filter(x=>x&&x.dataUrl):[];const shotMeta=shotList.map(x=>({platform:x.platform}));const a=await json(`You are PicPlanr's Account Strength analyst. Score the account fairly from 0 to 100 using only the supplied onboarding details and any supplied profile screenshots. Context: ${JSON.stringify(context)}. Profile: ${JSON.stringify(profile||{})}. Supplied screenshot platforms: ${JSON.stringify(shotMeta)}. A typed handle alone is not evidence that you viewed a live page. When no screenshot is supplied, the score is provisional and must not exceed 65. When screenshots are supplied, inspect only what is visibly legible and do not invent follower counts, engagement, posting frequency, recent content or performance. Score these seven categories: Profile clarity, Visual consistency, Content balance, Trust and proof, Video readiness, Posting consistency, Conversion readiness. For categories that cannot be verified, give a cautious score and clearly say what is missing. Return JSON with overall_score integer, score_label string, hook_message string, score_basis string, confidence string, next_action string, breakdown array of exactly 7 objects with category, score integer and reason, plus strengths, improvements and actions, each an array of exactly 3 short practical strings. The overall score should broadly reflect the seven category scores. Use British English. Do not use em dashes, en dashes or American spelling.`,shotList.map(x=>x.dataUrl));return res.json({audit:a})}
if(action==='image'){const a=await json(`You are PicPlanr's evidence-only image examiner. Accuracy is more important than creativity. Analyse exactly one image. Account context is background only and must never override what is actually visible. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile)}. Return JSON with: literal_summary (one neutral sentence describing only clearly visible content), confirmed_subjects array of objects with name and confidence (high/medium only), confirmed_setting string, confirmed_actions array, readable_text array containing only text that is genuinely legible, marketing_uses array of safe possible uses, grouping_keywords array, overall_confidence (high/medium/low), prohibited_inferences array, and unsuitable_for_caption boolean. Rules: do not infer an event type, relationship, pet-friendly policy, service, product, location, date, occasion, emotion, ownership or business capability unless directly visible or explicitly supplied in context. A visible dog proves only that a dog is visible; it does not prove the venue is pet-friendly. A wedding dress may suggest formal clothing but does not prove a wedding unless additional clear evidence exists. Never convert uncertain objects into specific items. If text is unclear, omit it.`,[image.dataUrl],'low');return res.json({analysis:a})}
if(action==='validate'){if(!group)return res.status(400).json({error:'Validation group is missing.'});const urls=(images||[]).map(x=>x.dataUrl);const evidence=(images||[]).map(x=>({image_id:x.image_id,analysis:x.analysis}));const v=await json(`You are PicPlanr's final accuracy auditor. Compare the proposed content group against the actual original images. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile)}. Proposed group: ${JSON.stringify(group)}. Earlier evidence: ${JSON.stringify(evidence)}. ${captionPolicy(context,profile)} Return JSON with group object containing: approved_for_display boolean, accuracy_status (checked or review), accuracy_notes array, title, format, objective, group_reason, schedule with day/time/reason, and captions array of exactly 3 objects using this exact structure:
    [{"label":"Engaging","text":"caption text"},{"label":"Informative","text":"caption text"},{"label":"Enquiry focused","text":"caption text"}].
    Every text value must be a non-empty string. 
Additional accuracy rules:
1. Do not describe the image sentence by sentence.
2. Do not begin with phrases such as "A closer look at", "This image shows", "Featuring", "Here we see" or "The photo captures".
3. Use the image as the visual context and use verified business information only when it is relevant.
4. Mention visible details naturally rather than listing everything in the image.
5. Never invent services, policies, offers, dates, availability, people, relationships, events, locations or results.
6. Use natural British English throughout.
 Correct every unsupported claim. Never remove all caption text. If a proposed caption is inaccurate, rewrite it into a safe accurate caption rather than returning an empty value. The title, reason and captions must be true for every image in the group. Never infer pet-friendly policy from a visible dog. Never claim the client provides styling, planning, catering or another service unless explicitly stated in context. Never identify an object more specifically than the image supports. If the images do not form a coherent group, set approved_for_display=false. Captions must sound natural, must not be image descriptions, and must use only verified facts plus explicit account context. Write all user-facing copy in British English. Use spellings such as colour, organise, personalised and centre. Never use any dash or hyphen character in captions, including compound words. Rewrite the wording with spaces, commas, full stops or separate sentences instead. `,urls);return res.json(v)}
if(action==='single_post'){if(!image?.dataUrl)return res.status(400).json({error:'Image is missing.'});const p=await json(`You are PicPlanr's conservative single-image post editor. This image must remain in the content plan because every uploaded image must be used exactly once. Analyse the original image directly. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile||{})}. Earlier evidence: ${JSON.stringify(image.analysis||{})}. ${captionPolicy(context,profile)} Return JSON with group object containing: title, format set to Single post, objective, group_reason, The title must be a short content angle, not a literal image description.  schedule with day, time and reason, accuracy_status set to checked or review, accuracy_notes array, and captions using this exact structure:
[{"label":"Engaging","text":"caption text"},{"label":"Informative","text":"caption text"},{"label":"Enquiry focused","text":"caption text"}].
Every text must be non-empty, natural British English and accurate to the visible image. 
Additional accuracy rules:
1. Do not describe the image sentence by sentence.
2. Do not begin with phrases such as "A closer look at", "This image shows", "Featuring", "Here we see" or "The photo captures".
3. Use the image as the visual context and use verified business information only when it is relevant.
4. Mention visible details naturally rather than listing everything in the image.
5. Never invent services, policies, offers, dates, availability, people, relationships, events, locations or results.
6. Use natural British English throughout.
 Do not invent services, policies, offers, dates, people, relationships, events or locations. Do not use em dashes or American spelling.`,[image.dataUrl]);return res.json(p)}
if(action==='story_image'){if(!image?.dataUrl)return res.status(400).json({error:'Story image is missing.'});const s=await json(`You are PicPlanr's strict Instagram Story image editor. Analyse this one original portrait image directly. Accuracy is more important than creativity. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile||{})}. Earlier evidence: ${JSON.stringify(image.analysis||{})}. First identify the single main visual subject. The Story title, description, frame instructions and all text options must focus on that main subject. Do not shift focus to background décor, venue features, services or policies unless they are clearly the main subject. Example rule: if a dog wearing formal clothing is the main subject, write about the dog and its outfit. Do not turn it into a venue décor, pet-friendly policy or event-planning Story. Never invent a name, event, relationship, service, offer, date, availability or customer action. Return JSON with story object containing: image_index, primary_subject, title, purpose, description, best_time, frames array of exactly 3 short instructions, and text_options using this exact structure:
[{"label":"Quick update","text":"short phrase"},{"label":"Engagement","text":"short question"},{"label":"Call to action","text":"short next step"}].
Every text value must be a non-empty string. Each option must be a short natural British English phrase, maximum 12 words. Quick update should state a simple visible truth. Engagement should ask a question directly related to the visible main subject. Call to action should use a safe generic action such as reply, react, follow or view more. Do not use em dashes, en dashes, American spelling or marketing clichés. If the image is ambiguous, use only the safest clearly visible main subject and still return three short, non-empty text options. Do not return an empty text_options array.`,[image.dataUrl]);return res.json(s)}
if(action==='stories'){const s=await json(`You are PicPlanr's Instagram Story strategist. Create practical Story updates only from the supplied portrait-image analyses. Stories are not feed captions. They should be short, current, conversational and useful for keeping customers or followers informed. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile)}. Portrait image analyses: ${JSON.stringify(images)}. Create 1-8 Story ideas. Use each image at most once unless there are very few portrait images. Never invent facts, dates, offers, events, availability, products or outcomes. Use only details present in the image analysis and supplied account context. Each Story must return: image_index, title, purpose, description, best_time, frames array of exactly 3 short instructions, and text_options array of exactly 3 objects. The three text option labels must be Quick update, Engagement, and Call to action. Each text must be a short phrase suitable as an Instagram Story overlay, ideally under 12 words and never more than 18 words. Write all user-facing copy in British English. Use spellings such as colour, organise, personalised and centre. Never use any dash or hyphen character in captions, including compound words. Rewrite the wording with spaces, commas, full stops or separate sentences instead.  Quick update should keep customers informed. Engagement should ask a natural question. Call to action should give one simple next step. Return JSON object with stories array.`);return res.json(s)}
if(action==='group'){const g=await json(`You are PicPlanr's conservative content planner. Group images using the stable image_id values exactly as supplied. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile)}. Evidence-only image analyses: ${JSON.stringify(images)}. ${captionPolicy(context,profile)} Rules: use only confirmed evidence. Never use an image in more than one group. Never mix images just because they share a broad business category. Group only when subjects, setting, event, visual sequence or theme clearly match. Do not infer pet-friendly policies, event styling services, planning services, products, dates, relationships, occasions or capabilities unless explicitly supplied in context. Every supplied image_id must appear in exactly one group. Never omit an image. If an image does not match another, create a conservative Single post for it. Create 1-50 groups. For each group return: title, image_ids array using exact supplied IDs. The title must be a short content angle, not a literal image description.  format (Single post or Carousel), objective, group_reason, schedule with day, time and reason, and captions array of exactly 3 objects using this exact structure:
    [{"label":"Engaging","text":"caption text"},{"label":"Informative","text":"caption text"},{"label":"Enquiry focused","text":"caption text"}].
    Every text value must be a non-empty string. 
Additional accuracy rules:
1. Do not describe the image sentence by sentence.
2. Do not begin with phrases such as "A closer look at", "This image shows", "Featuring", "Here we see" or "The photo captures".
3. Use the image as the visual context and use verified business information only when it is relevant.
4. Mention visible details naturally rather than listing everything in the image.
5. Never invent services, policies, offers, dates, availability, people, relationships, events, locations or results.
6. Use natural British English throughout.
 Captions must not list everything visible. Captions must not claim the business offers a service unless that service appears in context. Enquiry focused captions may use a relevant action such as enquire, book, view more or visit the website, but must not invent offers or availability. Return JSON object with groups array.`);return res.json(g)}return res.status(400).json({error:'Unknown action.'})}catch(e){
  console.error(e);
  if(e?.statusCode===402)return sendBillingError(res,e);
  if(e?.statusCode===401)return sendWorkspaceError(res,e,'Sign in to use PicPlanr AI.');

  const status=Number(e?.status||500);
  const code=String(e?.code||e?.error?.code||'').toLowerCase();

  if(status===401){
    return res.status(503).json({
      error:'PicPlanr is temporarily unavailable. Please try again shortly.',
      retryable:false
    });
  }

  if(code==='insufficient_quota'||code==='billing_hard_limit_reached'){
    return res.status(503).json({
      error:'PicPlanr is temporarily unable to complete this analysis. Your files remain selected.',
      retryable:false
    });
  }

  if(status===429||status===408||status===409||status>=500){
    return res.status(503).json({
      error:'PicPlanr is still processing a high volume of content. It will retry automatically.',
      retryable:true
    });
  }

  return res.status(status<600?status:500).json({
    error:'PicPlanr could not complete this step. Your files remain selected.',
    retryable:false
  });
}}
